//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boran.Models
{
    using System;
    using System.Collections.Generic;

    public partial class db
    {
        public int Id { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get ;  set; }
        public string OrderPriority { get; set; }
        public Nullable<double> Discount { get; set;  }
        public string ShipMode { get; set; }
        public Nullable<double> UnitPrice { get; set ; }
        public Nullable<double> UnitShippingCost { get; set; }
        public string CustomerName { get; set; }
        public string Province { get; set; } 
        public string Region { get; set; }
        public string CustomerSegment { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubCategory { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public string ProductContainer { get; set; }
        public Nullable<double> ProductBaseMargin { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
    }
}
